Consistent hashing
iqoption/rpcng pull request #5
Opened 2019-01-23 13:11 UTC by Irioth

2019-01-23 17:16 UTC, lukashes requested changes

2019-01-23 17:16 UTC, lukashes commented on selector.go
> +		defer func() { c.stopped <- struct{}{} }()
Может просто закрыть канал? Кажется, больше никто в него писать не может

2019-01-23 17:16 UTC, lukashes commented on selector.go
> +				c.stop(clients[i])
Ключики `i` упорядочены и чтобы закрыть коннекты, можно не обходить весь набор клиентов, а лишь ограничитаться теми что 0 <= j <= i

2019-01-23 17:16 UTC, lukashes commented on selector.go
> +	s := c.getServices(tag, c.getDiscovered(), nil)
Внутри getDiscovered() используется мьютекс `c.mux`, дедлоков не будет?

2019-01-24 13:19 UTC, Irioth commented on selector.go
> +	s := c.getServices(tag, c.getDiscovered(), nil)
тут можно напрямую, еще избавился от баги что клиенты не закрывались если мы сначала создали без consistent hash и потом с consistent hash

2019-01-25 13:40 UTC, lukashes requested changes

2019-01-25 13:40 UTC, lukashes commented on consistenthash/consistenthash.go
> +	return m.hashMap[m.keys[idx]]
Сам кусок кода с поиском ближайшего хэше можно вынести в отдельный метод, так как он полностью диблируется в методах `Get` и `GetUint64`

2019-01-25 13:40 UTC, lukashes commented on selector.go
> +			c.log.Error("failure to replase tagged", "error", err)
replace

2019-02-01 10:09 UTC, merged